name: model-supervisé RL
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run code
         runs:|
          docker run --name devtest -v myvol2:/app -p 8080:8080 hhurchand/bdeb_mlflow_boston:latest
      - name: Upload mlruns
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: mlruns

