name: model-supervisé RL
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shrink/actions-docker-extract@v1
        with:
          image: hhurchand/bdeb_mlflow_boston:latest
          path: '/app'
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: dist
