name: Docker Image CI

on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
       docker build . --file Dockerfile --tag hhurchand/bdeb_tp1:v0
       pip install -r requirements.txt
       pip install mlflow

