name: Docker Image CI

on:
  push:
    branches: [ main ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
       echo "Hello World"
       docker build . --file Dockerfile --tag hhurchand/bdeb_tp1:v0
       docker push hhurchand/bdeb_tp1:v0
       
