name: Docker Image CI

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          repository: hhurchand/bdeb_mlflow_boston
          tags: latest
      - uses: shrink/actions-docker-extract@v1
        with:
          image: my-example-image:latest
          path: /app/.
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.extract.outputs.destination }}
          name: dist
