name: model-supervisé RL
on: [push]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Build
    steps:
      - uses: actions/checkout@v2  
      - name: Build Image
        run: |
          docker run hhurchand/bdeb_mlflow_boston:latest
          mkdir -p path/to/artifacts
          docker save app/mlruns > path/to/artifacts/ml
          echo "$DOCKER_FULLTAG" > path/to/artifacts/docker-tag
          
      - name: Temporarily save Docker file
        uses: actions/upload-artifact@v2
        with:
          name: docker-artifact
          path: path/to/artifacts
          retention-days: 1
