name: model-supervisé RL
on: [push]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Build
    steps:
      - uses: actions/checkout@v2  
      - name: Build Image
        run: |
          docker run hhurchand/bdeb_mlflow_boston:latest
      - name: Upload all 
        uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: .
